### ISSUE TITLE
Babel config json should be editable

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#69]
Parse the text within the babel config to allow two way linking between source files and the config.

![image](https://user-images.githubusercontent.com/318295/89247466-fd6f4e00-d5d2-11ea-8d80-c1591759bd42.png)

This creates some weird problems, right? Like what to those switches mean now? How does everything behave?

Switches:
- indicate that a plugin is being included remotely
- when they're turned on,
    - include the <script>
    - .append(plugin, pluginConfig)` to babel json
- when they're turned off
    - remove the <script> tag

Code Editor (optional)
- on every update
    - parse the plugins json
    - each plugin
        - plugin is in default list of plugins?
            - yes
                - if the switch is not on
                    - update the switch
            - no
                - (later) include it remotely?

This is going to require a small refactor, with the main mission of **toggle plugins based on babel config**.

What happens to the database if we give it a plugin that isn't from our list? Anything?

**Comment by garrettluu** [comment]
> - when they're turned on,
>     - include the <script>
> - when they're turned off
>     - remove the <script> tag

I disagree slightly with this approach; I think the *presence* of a switch should indicate that the <script> is included, and the switch should merely control whether the specific plugin gets included in the config. It might be a hassle since we would also need to call `Babel.registerPlugin` everytime we include a new <script>.

I think in the future when we allow importing external plugins, the flow would go something like this:
import plugin → a switch for that plugin appears, but off → choose to include/exclude it by turning the switch on or off

Thoughts?

**Comment by ianjennings** [comment]
#98

**Comment by garrettluu** [comment]
Is this issue still relevant? #98 seems to partially address this, but the switches don't change when the config is manually edited.
